# 基于官方 OpenJDK 11 镜像
FROM mcr.microsoft.com/devcontainers/ubuntu:base
# 安装任何额外的工具或依赖项
# 例如，安装 Maven（这里仅作为示例，因为我们在 postCreateCommand 中也做了安装）
RUN apt-get update && apt-get install -y maven

# 设置工作目录
#WORKDIR /workspace

